CREATE TABLE PRODUCT (
    Id NUMBER PRIMARY KEY,
    Name VARCHAR2(20) NOT NULL,
    Price NUMBER CHECK (Price > 0),
    Category VARCHAR2(20)
);

CREATE TABLE CUSTOMER (
    Id NUMBER PRIMARY KEY,
    FullName VARCHAR2(20) NOT NULL,
    Email VARCHAR2(20) UNIQUE,
    Phone VARCHAR2(20) UNIQUE
);

CREATE TABLE ORDERS (
    Id NUMBER PRIMARY KEY,
    CustomerId NUMBER,
    ProductId NUMBER,
    Quantity NUMBER DEFAULT 1,
    OrderDate DATE DEFAULT SYSDATE,
    FOREIGN KEY (CustomerId) REFERENCES CUSTOMER(Id),
    FOREIGN KEY (ProductId) REFERENCES PRODUCT(Id)
); 